Инкремент 3
izaake/go-shortener-tpl pull request #3
Opened 2022-11-28 17:11 UTC by izaake

2022-11-29 21:57 UTC, avhitrov requested changes
Обожаю лаконичные решения. Но на следующих итерациях при дальнейшем развитии кода рекомендую на каждый тип запроса в раутере создавать отдельную хендлер-функцию. Количество реакций сервера будет заметно расширяться, и единственный хендлер распухнет до невозможности его поддерживать. Пока в этом необходимости нет, решение мне нравится.

Замечания касаются работы с ресурсами и данными. Тело post-запроса после чтения рекомендуется закрывать (https://golangbyexample.com/resposne-body-closed-golang/)
Мапы необходимо защищать мьютексами.

2022-11-29 21:57 UTC, avhitrov commented on internal/handlers/handler.go
> +		}
defer r.Body.Close()

2022-11-29 21:57 UTC, avhitrov commented on internal/handlers/handler.go
> +var str = map[string]string{}
Мапа - ссылочная структура, очень чувствительная к конкурентному обращению со стороны нескольких горутин. Каждый запрос - это отдельная горутина, поэтому чтение и запись в мапу надо обвешивать блокировками иначе могут возникнуть гонки по данным, когда один запрос портит результаты другого. Для этого подойдет sync.RWMutex, позволяющий организовать неблокирующее чтение (RWLock-RWUnlock). На данном этапе достаточно одного глобального мьютекса.

2022-12-01 20:07 UTC, izaake commented on internal/handlers/handler.go
> +var str = map[string]string{}
спасибо! добавила

2022-12-01 21:33 UTC, avhitrov requested changes
Почти все отлично, кроме одного вызова блокировки.

2022-12-01 21:33 UTC, avhitrov commented on internal/handlers/handler.go
> +		lock.RLock()
```suggestion
		lock.Lock()
```
Здесь происходит запись в структуру, поэтому лочить надо полноценно. RLock используется для ускорения совместного чтения, так как два им более одновременных RLock друг друга не задерживают.

2022-12-01 21:33 UTC, avhitrov commented on internal/handlers/handler.go
> +		lock.RUnlock()
```suggestion
		lock.Unlock()
```

2022-12-01 21:38 UTC, avhitrov commented on internal/handlers/handler.go
> +		lock.RLock()
https://medium.com/a-journey-with-go/go-concurrency-access-with-maps-part-iii-8c0a0e4eb27e
https://gobyexample.com/mutexes

2022-12-02 08:03 UTC, izaake commented on internal/handlers/handler.go
> +		lock.RLock()
поняла, спасибо за пояснения!

2022-12-02 19:18 UTC, avhitrov approved these changes

2022-12-04 10:49 UTC, merged